orbs: # declare what orbs we are going to use
  node: circleci/node@5.0.3 # the node orb provides common node-related configuration 
  browser-tools: circleci/browser-tools@1.4.0

version: 2.1 # using 2.1 provides access to orbs and other features

jobs:
  build:
    executor: node/default
    working_directory: ~/danger-demo-app
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: cd app && npm install
      - run: cd app && npm run build

  test: #run unit tests
    working_directory: ~/app
    executor: node/default
    steps:
      - browser-tools/install-chrome
      - checkout  
      - run: cd app && npm install
      - run: cd app && npm run build
      - run: cd app && npm run test-headless 

  e2eTest: #run end to end tests
    executor: node/default
    working_directory: ~/danger-demo-app
    steps:
      - browser-tools/install-chrome
      - checkout  
      - run: cd app && npm install
      - run: cd app && npm run build
      - run: cd app && npm run e2e 
      - store_artifacts: 
          path: ./danger-demo-app/tmp


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - e2eTest